### ISSUE TITLE
Sample image

### ISSUE THREAD

**Issue by pbeukema** [allenai/global_fishing_capacity_detector#1]
Build/inference worked well. Readme is easy to follow. 

I have a few very minor comments. 
1. I would consider adding an example path to an image that can be downloaded directly to run inference against (provided user has access to the gs bucket). Alternatively, perhaps there is a sample image that is already in the public domain that we can include in the repo). Or include an image in the github repo -- assuming that some other version of this gets open sourced. 
2. I would consider omitting entirely the training section from the open sourced codebase, since I don't think any user who has access to this repo who isn't Minderoo will get access to the imagery.
3. I would consider including a script that enables executing all of the download/build steps automatically, perhaps via a docker-compose.yaml or similar). So that one can build everything as intended (including the weights/example image/etc), without having to execute a bunch of commands (untested example compose file below).  
4. Perhaps add "Recommended" to this line: https://github.com/allenai/global_fishing_capacity_detector?tab=readme-ov-file#usage-with-docker-container
5. Add comment on how long inference should take on XX GPU. 

```yaml 

version: '3.8'
services:
  gfcd:
    image: gfcd:latest
    build:
      context: .
    runtime: nvidia  # Enable GPU support
    shm_size: 16g
    volumes:
      - ./global_fishing_capacity_detector:/vol
    command: >
      bash -c "
      # Download the detector weights if not present
      if [ ! -f /vol/detector.pth ]; then
        echo 'Downloading detector weights...';
        wget -O /vol/detector.pth https://example.com/path-to-checkpoint/detector.pth;
      fi
      
      # Download the example image if not present
      if [ ! -f /vol/example-image.tif ]; then
        echo 'Downloading example image...';
        wget -O /vol/example-image.tif https://example.com/path-to-example-image/example-image.tif;
      fi

      # Run the prediction pipeline
      python docker_entrypoint.py predict /vol/example-image.tif /vol/scene-visual-output/
      "

```
